version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: todos-api-dev
    restart: unless-stopped
    tty: true
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - database
      - redis
    ports:
      - 3050:3050
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules

  database:
    image: postgres:13-alpine3.16
    container_name: todos-db-dev
    restart: unless-stopped
    tty: true
    stdin_open: true
    env_file:
      - .database.env
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis

volumes:
  data:
    name: todos_data
